export const travisDemo = {
  manufacturer: "Travis Industries",
  poweredBy: "Hearth-OS",
  dealerNetworkName: "Travis Dealer Commerce Network",
  demoDealer: "Cascade Hearth & Home",
  territory: "Pacific Northwest Demo Territory",
  period: "Demo month: April 2026",
  brands: ["Fireplace Xtrordinair", "Lopi", "DaVinci Custom Fireplaces", "Tempest Torch"],
  kpis: [
    { label: "Dealer ecommerce revenue", value: "$184.6K", note: "Website-attributed quote/order pipeline", tone: "green" },
    { label: "Service requests captured", value: "73", note: "Install, maintenance, warranty, repair", tone: "amber" },
    { label: "Parts & accessory demand", value: "$41.2K", note: "Replacement parts + finish packages", tone: "blue" },
    { label: "Card volume opportunity", value: "$128.9K", note: "Payment processing revenue-share pool", tone: "purple" },
  ],
  ecommerceEvents: [
    {
      id: "WEB-1048",
      customer: "Megan Carter",
      source: "Travis-powered dealer site",
      type: "Quote request",
      product: "Fireplace Xtrordinair 4415 HO GSR2",
      sku: "FPX-4415-HO-GSR2",
      value: "$8,940",
      status: "Estimate draft ready",
      nextStep: "Confirm facing kit and vent path",
    },
    {
      id: "WEB-1049",
      customer: "North Ridge Builders",
      source: "Builder portal",
      type: "Multi-unit bid",
      product: "Lopi Answer NexGen-Fyre Wood Insert x 6",
      sku: "LOPI-ANSWER-NG-6PK",
      value: "$31,680",
      status: "Assigned to trade desk",
      nextStep: "Generate builder quote packet",
    },
    {
      id: "WEB-1050",
      customer: "Caleb Morris",
      source: "Parts finder",
      type: "Parts fitment",
      product: "Lopi blower replacement kit",
      sku: "LOPI-BLOWER-KIT-DEMO",
      value: "$489",
      status: "Fitment verification needed",
      nextStep: "Request model/serial photo",
    },
  ],
  serviceRequests: [
    { window: "Today 9:00 AM", customer: "Sarah Jensen", job: "Annual service - Lopi Endeavor", tech: "Alex R.", status: "Scheduled" },
    { window: "Today 1:30 PM", customer: "Horizon Remodel", job: "FPX insert measure + vent inspection", tech: "Mia T.", status: "Dispatched" },
    { window: "Tomorrow", customer: "Dawson Lake House", job: "DaVinci linear fireplace consult", tech: "Chris M.", status: "Needs confirmation" },
  ],
  paymentModel: [
    { label: "Dealer card volume", value: "$128,900" },
    { label: "Illustrative net processing spread", value: "35 bps" },
    { label: "Monthly platform revenue pool", value: "$451" },
    { label: "Manufacturer rev-share scenario", value: "10–20%" },
  ],
  analytics: [
    "Top requested Travis SKU families by dealer market",
    "Service and warranty demand by model line",
    "Parts demand signals before dealers stock out",
    "Dealer ecommerce conversion and abandoned quote tracking",
    "Payment volume available for manufacturer/dealer revenue-share programs",
  ],
};

export type TravisDemo = typeof travisDemo;
