"use client";

import { useEffect, useMemo, useState } from "react";
import Sidebar from "@/components/layout/Sidebar";
import Header from "@/components/layout/Header";

type Entry = { id: string; techId: string; techName?: string; clockInAt: string; clockOutAt?: string | null; totalMinutes?: number | null; status: "open" | "closed"; editNote?: string };
type Tech = { id: string; name: string; email?: string; role?: string; color?: string };
type PayrollResponse = { approvals: any[]; reports: any[]; adjustments?: any[]; runs?: any[] };

const DEFAULT_PAY_PROFILES: Record<string, { rate: number; type: "hourly" | "salary"; directDeposit: boolean; accountLast4: string; routingLast4: string }> = {
  "tech-fx-001": { rate: 42, type: "hourly", directDeposit: true, accountLast4: "1842", routingLast4: "0210" },
  "tech-fx-002": { rate: 38, type: "hourly", directDeposit: true, accountLast4: "0147", routingLast4: "0210" },
  "tech-fx-003": { rate: 27, type: "hourly", directDeposit: false, accountLast4: "", routingLast4: "" },
  "tech-fx-004": { rate: 32, type: "hourly", directDeposit: true, accountLast4: "0166", routingLast4: "0210" },
  "tech-fx-005": { rate: 40, type: "hourly", directDeposit: true, accountLast4: "0190", routingLast4: "0210" },
  "tech-fx-006": { rate: 36, type: "hourly", directDeposit: true, accountLast4: "0172", routingLast4: "0210" },
};
function getWeekStart(date: Date) { const d = new Date(date); d.setDate(d.getDate() - ((d.getDay() + 6) % 7)); d.setHours(0,0,0,0); return d; }
function isoDate(d: Date) { return d.toISOString().slice(0, 10); }
function money(n: number) { return `$${n.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
function hours(min: number) { return (min / 60).toFixed(2); }

export default function PayrollPage() {
  const [weekStart, setWeekStart] = useState(getWeekStart(new Date()));
  const [entries, setEntries] = useState<Entry[]>([]);
  const [techs, setTechs] = useState<Tech[]>([]);
  const [payroll, setPayroll] = useState<PayrollResponse>({ approvals: [], reports: [], adjustments: [], runs: [] });
  const [payProfiles, setPayProfiles] = useState(DEFAULT_PAY_PROFILES);
  const [bank, setBank] = useState({ name: "Travis Industries Demo Operating", routing: "021000021", account: "9876541842", verified: true });
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState<string | null>(null);
  const [adjustment, setAdjustment] = useState({ techId: "", type: "bonus", label: "Spiff / bonus", amount: "250" });
  const [message, setMessage] = useState("");
  const weekIso = isoDate(weekStart);
  const weekEnd = useMemo(() => { const d = new Date(weekStart); d.setDate(d.getDate() + 6); return d; }, [weekStart]);

  async function load() {
    setLoading(true);
    try {
      const [entryRes, techRes, payrollRes] = await Promise.all([fetch(`/api/time/entries?weekOf=${weekIso}`), fetch("/api/techs?activeOnly=true"), fetch(`/api/time/payroll?weekStart=${weekIso}`)]);
      const entryData = await entryRes.json(); const techData = await techRes.json(); const payrollData = await payrollRes.json();
      setEntries(entryData.entries || []); setTechs(techData.techs || []); setPayroll({ approvals: payrollData.approvals || [], reports: payrollData.reports || [], adjustments: payrollData.adjustments || [], runs: payrollData.runs || [] });
    } finally { setLoading(false); }
  }
  useEffect(() => { load(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [weekIso]);

  const rows = useMemo(() => techs.map((tech) => {
    const techEntries = entries.filter((e) => e.techId === tech.id);
    const totalMinutes = techEntries.reduce((sum, e) => sum + (e.status === "open" ? Math.max(0, Math.round((Date.now() - new Date(e.clockInAt).getTime()) / 60000)) : Number(e.totalMinutes || 0)), 0);
    const regularMinutes = Math.min(totalMinutes, 2400);
    const overtimeMinutes = Math.max(0, totalMinutes - 2400);
    const profile = payProfiles[tech.id] || { rate: 34, type: "hourly", directDeposit: false, accountLast4: "", routingLast4: "" };
    const rate = Number(profile.rate || 0);
    const gross = regularMinutes / 60 * rate + overtimeMinutes / 60 * rate * 1.5;
    const adjustmentTotal = (payroll.adjustments || []).filter((a) => a.tech_id === tech.id).reduce((sum, a) => sum + Number(a.amount || 0), 0);
    const taxableGross = gross + adjustmentTotal;
    const employeeTaxes = taxableGross * 0.1765;
    const net = taxableGross - employeeTaxes;
    const employerTaxes = taxableGross * 0.0925;
    const approved = (payroll.approvals || []).some((a) => a.tech_id === tech.id);
    return { tech, techEntries, totalMinutes, regularMinutes, overtimeMinutes, rate, profile, gross, adjustmentTotal, taxableGross, employeeTaxes, net, employerTaxes, approved };
  }), [techs, entries, payroll]);

  const totals = rows.reduce((acc, r) => ({ hours: acc.hours + r.totalMinutes / 60, gross: acc.gross + r.taxableGross, taxes: acc.taxes + r.employeeTaxes, net: acc.net + r.net, employerTaxes: acc.employerTaxes + r.employerTaxes, approved: acc.approved + (r.approved ? 1 : 0) }), { hours: 0, gross: 0, taxes: 0, net: 0, employerTaxes: 0, approved: 0 });

  async function approve(row: typeof rows[number]) { await fetch("/api/time/payroll", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "approve", techId: row.tech.id, techName: row.tech.name, weekStart: weekIso, totalMinutes: row.totalMinutes }) }); await load(); }
  async function addAdjustment() { const tech = techs.find((t) => t.id === adjustment.techId) || rows[0]?.tech; if (!tech) return; await fetch("/api/time/payroll", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "adjustment", weekStart: weekIso, techId: tech.id, techName: tech.name, type: adjustment.type, label: adjustment.label, amount: Number(adjustment.amount || 0), taxable: true }) }); setAdjustment({ ...adjustment, techId: "", amount: "250" }); await load(); }
  async function exportPayroll() { const approved = rows.filter((r) => r.approved).map((r) => ({ techId: r.tech.id, techName: r.tech.name, totalMinutes: r.totalMinutes, rate: r.rate })); if (!approved.length) { setMessage("Approve at least one employee before generating payroll."); return; } const res = await fetch("/api/time/payroll", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "send_report", weekStart: weekIso, approvals: approved }) }); const data = await res.json(); if (data.csv) { const url = URL.createObjectURL(new Blob([data.csv], { type: "text/csv" })); const a = document.createElement("a"); a.href = url; a.download = `hearth-os-payroll-${weekIso}.csv`; a.click(); URL.revokeObjectURL(url); } setMessage(`Payroll export generated for ${data.techCount || approved.length} employees.`); await load(); }
  async function runPayroll(status = "ready_to_submit") { await fetch("/api/time/payroll", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "run_payroll", weekStart: weekIso, status, payDate: isoDate(new Date()), grossPay: totals.gross, employerTaxes: totals.employerTaxes, netPay: totals.net, employeeCount: rows.length }) }); setMessage(status === "submitted" ? "Demo payroll marked submitted." : "Payroll run staged and ready for approval."); await load(); }
  function updatePayProfile(techId: string, patch: Partial<{ rate: number; type: "hourly" | "salary"; directDeposit: boolean; accountLast4: string; routingLast4: string }>) {
    setPayProfiles((prev) => ({ ...prev, [techId]: { ...(prev[techId] || DEFAULT_PAY_PROFILES[techId] || { rate: 34, type: "hourly", directDeposit: false, accountLast4: "", routingLast4: "" }), ...patch } }));
  }
  async function fundAndPayPayroll() {
    if (!bank.verified) { setMessage("Verify the company bank account before paying payroll."); return; }
    if (totals.approved < rows.length) { setMessage("Approve every employee before funding payroll."); return; }
    await runPayroll("paid");
    setMessage(`Payroll funded from ${bank.name} and ${money(totals.net)} net pay queued for employees.`);
  }

  return <div className="flex h-screen overflow-hidden" style={{ background: "var(--color-bg)" }}><Sidebar /><div className="flex-1 flex flex-col overflow-hidden"><Header /><main className="flex-1 overflow-y-auto"><div className="max-w-[1600px] mx-auto p-6 space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.2em]" style={{ color: "var(--color-travis-red)" }}>Payroll Command Center</p><h1 className="text-3xl font-black" style={{ color: "var(--color-text-primary)" }}>Run payroll inside Hearth-OS</h1><p className="text-sm mt-1" style={{ color: "var(--color-text-muted)" }}>QuickBooks Payroll-style workflow: review time, approve employees, add bonuses/reimbursements, calculate taxes, export, and stage payroll runs.</p></div><div className="flex items-center gap-2"><button onClick={() => { const d = new Date(weekStart); d.setDate(d.getDate()-7); setWeekStart(getWeekStart(d)); }} className="btn">←</button><div className="px-4 py-2 rounded-lg text-sm font-semibold" style={{ background: "var(--color-surface-1)", border: "1px solid var(--color-border)", color: "var(--color-text-primary)" }}>{weekIso} – {isoDate(weekEnd)}</div><button onClick={() => { const d = new Date(weekStart); d.setDate(d.getDate()+7); setWeekStart(getWeekStart(d)); }} className="btn">→</button></div></div>
    <div className="grid grid-cols-2 lg:grid-cols-5 gap-3"><Kpi label="Employees" value={String(rows.length)} hint={`${totals.approved} approved`} /><Kpi label="Total Hours" value={totals.hours.toFixed(2)} hint="regular + overtime" /><Kpi label="Gross Pay" value={money(totals.gross)} hint="wages + adjustments" /><Kpi label="Employee Taxes" value={money(totals.taxes)} hint="demo withholding" /><Kpi label="Net Pay" value={money(totals.net)} hint={`Employer tax ${money(totals.employerTaxes)}`} /></div>
    <div className="grid grid-cols-1 xl:grid-cols-[1fr_360px] gap-5"><section className="rounded-2xl overflow-hidden" style={{ background: "var(--color-surface-1)", border: "1px solid var(--color-border)" }}><div className="px-5 py-4 flex justify-between items-center" style={{ borderBottom: "1px solid var(--color-border)" }}><div><h2 className="font-bold" style={{ color: "var(--color-text-primary)" }}>Payroll worksheet</h2><p className="text-xs" style={{ color: "var(--color-text-muted)" }}>Click a row to inspect time entries and payroll detail.</p></div><button onClick={() => rows.forEach((r) => !r.approved && approve(r))} className="px-3 py-2 rounded-lg text-sm font-semibold text-white" style={{ background: "#d65050" }}>Approve all</button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead style={{ background: "var(--color-surface-2)", color: "var(--color-text-muted)" }}><tr><Th>Employee</Th><Th>Hours</Th><Th>Rate</Th><Th>Gross</Th><Th>Adj.</Th><Th>Taxes</Th><Th>Net</Th><Th>Status</Th></tr></thead><tbody>{loading ? <tr><td colSpan={8} className="p-8 text-center">Loading…</td></tr> : rows.map((r) => <tr key={r.tech.id} onClick={() => setSelected(r.tech.id)} className="cursor-pointer" style={{ borderTop: "1px solid var(--color-border)", background: selected === r.tech.id ? "rgba(214,80,80,0.08)" : undefined }}><td className="px-4 py-3"><div className="font-semibold" style={{ color: "var(--color-text-primary)" }}>{r.tech.name}</div><div className="text-xs" style={{ color: "var(--color-text-muted)" }}>{r.tech.email || r.tech.role}</div></td><td className="px-4 py-3" style={{ color: "var(--color-text-secondary)" }}>{hours(r.regularMinutes)} reg<br/><span className="text-xs">{hours(r.overtimeMinutes)} OT</span></td><td className="px-4 py-3">{money(r.rate)}/hr</td><td className="px-4 py-3 font-semibold">{money(r.gross)}</td><td className="px-4 py-3">{money(r.adjustmentTotal)}</td><td className="px-4 py-3">{money(r.employeeTaxes)}</td><td className="px-4 py-3 font-bold" style={{ color: "#16A34A" }}>{money(r.net)}</td><td className="px-4 py-3">{r.approved ? <span className="pill good">Approved</span> : <button onClick={(e) => { e.stopPropagation(); approve(r); }} className="pill action">Approve</button>}</td></tr>)}</tbody></table></div></section>
    <aside className="space-y-4"><Panel title="Payroll actions"><div className="space-y-2"><button onClick={exportPayroll} className="actionBtn">Export payroll CSV</button><button onClick={() => runPayroll("ready_to_submit")} className="actionBtn">Stage payroll run</button><button onClick={() => runPayroll("submitted")} className="actionBtn danger">Mark submitted</button>{message && <p className="text-xs" style={{ color: "#16A34A" }}>{message}</p>}</div></Panel><Panel title="Adjustment / bonus"><select value={adjustment.techId} onChange={(e) => setAdjustment({ ...adjustment, techId: e.target.value })} className="input"><option value="">Select employee</option>{techs.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</select><input value={adjustment.label} onChange={(e) => setAdjustment({ ...adjustment, label: e.target.value })} className="input" /><input type="number" value={adjustment.amount} onChange={(e) => setAdjustment({ ...adjustment, amount: e.target.value })} className="input" /><button onClick={addAdjustment} className="actionBtn">Add adjustment</button></Panel><Panel title="Company bank account"><input value={bank.name} onChange={(e) => setBank({ ...bank, name: e.target.value })} className="input" /><input value={bank.routing} onChange={(e) => setBank({ ...bank, routing: e.target.value })} className="input" placeholder="Routing number" /><input value={bank.account} onChange={(e) => setBank({ ...bank, account: e.target.value })} className="input" placeholder="Account number" /><button onClick={() => setBank({ ...bank, verified: true })} className="actionBtn">{bank.verified ? "Bank verified" : "Verify bank"}</button><button onClick={fundAndPayPayroll} className="actionBtn danger">Fund payroll / pay employees</button><p className="text-xs" style={{ color: "var(--color-text-muted)" }}>Demo ACH rail: stores funding account, validates approval readiness, and creates a paid payroll run.</p></Panel><Panel title="Payroll runs"><div className="space-y-2">{(payroll.runs || []).length === 0 && <p className="text-xs" style={{ color: "var(--color-text-muted)" }}>No staged runs yet.</p>}{(payroll.runs || []).map((run) => <div key={run.id} className="p-3 rounded-lg" style={{ background: "var(--color-surface-2)", color: "var(--color-text-secondary)" }}><div className="font-semibold">{run.status}</div><div className="text-xs">Gross {money(Number(run.gross_pay || 0))} · Net {money(Number(run.net_pay || 0))}</div></div>)}</div></Panel></aside></div>
    <section className="rounded-2xl overflow-hidden" style={{ background: "var(--color-surface-1)", border: "1px solid var(--color-border)" }}><div className="px-5 py-4" style={{ borderBottom: "1px solid var(--color-border)" }}><h2 className="font-bold" style={{ color: "var(--color-text-primary)" }}>Employee pay setup</h2><p className="text-xs" style={{ color: "var(--color-text-muted)" }}>Edit pay rates, salary/hourly type, and direct deposit status before running payroll.</p></div><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3 p-4">{rows.map((r) => <div key={r.tech.id} className="p-4 rounded-xl" style={{ background: "var(--color-surface-2)", border: "1px solid var(--color-border)" }}><div className="font-semibold" style={{ color: "var(--color-text-primary)" }}>{r.tech.name}</div><div className="grid grid-cols-2 gap-2 mt-3"><select value={r.profile.type} onChange={(e) => updatePayProfile(r.tech.id, { type: e.target.value as any })} className="input"><option value="hourly">Hourly</option><option value="salary">Salary</option></select><input type="number" value={r.profile.rate} onChange={(e) => updatePayProfile(r.tech.id, { rate: Number(e.target.value) })} className="input" /></div><label className="flex items-center gap-2 text-xs" style={{ color: "var(--color-text-secondary)" }}><input type="checkbox" checked={r.profile.directDeposit} onChange={(e) => updatePayProfile(r.tech.id, { directDeposit: e.target.checked })} /> Direct deposit</label><div className="grid grid-cols-2 gap-2 mt-2"><input value={r.profile.routingLast4} onChange={(e) => updatePayProfile(r.tech.id, { routingLast4: e.target.value })} className="input" placeholder="Routing last 4" /><input value={r.profile.accountLast4} onChange={(e) => updatePayProfile(r.tech.id, { accountLast4: e.target.value })} className="input" placeholder="Account last 4" /></div></div>)}</div></section>

    {selected && <section className="rounded-2xl p-5" style={{ background: "var(--color-surface-1)", border: "1px solid var(--color-border)" }}><h2 className="font-bold mb-3" style={{ color: "var(--color-text-primary)" }}>Employee detail</h2>{rows.filter((r) => r.tech.id === selected).map((r) => <div key={r.tech.id} className="grid grid-cols-1 lg:grid-cols-2 gap-4"><div><h3 className="font-semibold" style={{ color: "var(--color-text-primary)" }}>{r.tech.name}</h3><p className="text-sm" style={{ color: "var(--color-text-muted)" }}>Regular {hours(r.regularMinutes)} · Overtime {hours(r.overtimeMinutes)} · Gross {money(r.taxableGross)}</p><div className="mt-3 space-y-2">{r.techEntries.map((e) => <div key={e.id} className="p-3 rounded-lg text-sm" style={{ background: "var(--color-surface-2)", color: "var(--color-text-secondary)" }}>{new Date(e.clockInAt).toLocaleString()} → {e.clockOutAt ? new Date(e.clockOutAt).toLocaleString() : "Clocked in"}<br/><span className="text-xs">{e.editNote || e.status}</span></div>)}</div></div><div className="grid grid-cols-2 gap-3"><Kpi label="Gross" value={money(r.taxableGross)} /><Kpi label="Employee taxes" value={money(r.employeeTaxes)} /><Kpi label="Net" value={money(r.net)} /><Kpi label="Employer taxes" value={money(r.employerTaxes)} /></div></div>)}</section>}
    <style jsx>{`.btn{padding:8px 12px;border-radius:10px;background:var(--color-surface-1);border:1px solid var(--color-border);color:var(--color-text-secondary)}.input{width:100%;padding:9px 10px;border-radius:10px;background:var(--color-surface-2);border:1px solid var(--color-border);color:var(--color-text-primary);margin-bottom:8px}.actionBtn{width:100%;padding:10px 12px;border-radius:10px;background:#d65050;color:white;font-weight:700;font-size:13px}.actionBtn.danger{background:#111}.pill{display:inline-flex;padding:5px 9px;border-radius:999px;font-size:11px;font-weight:800}.pill.good{background:rgba(22,163,74,.15);color:#16A34A}.pill.action{background:rgba(214,80,80,.15);color:#d65050}`}</style>
  </div></main></div></div>;
}
function Kpi({ label, value, hint }: { label: string; value: string; hint?: string }) { return <div className="p-4 rounded-xl" style={{ background: "var(--color-surface-1)", border: "1px solid var(--color-border)" }}><p className="text-[11px] uppercase tracking-wide" style={{ color: "var(--color-text-muted)" }}>{label}</p><p className="text-2xl font-black mt-1" style={{ color: "var(--color-text-primary)" }}>{value}</p>{hint && <p className="text-xs mt-1" style={{ color: "var(--color-text-muted)" }}>{hint}</p>}</div>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-2xl p-4" style={{ background: "var(--color-surface-1)", border: "1px solid var(--color-border)" }}><h3 className="font-bold mb-3" style={{ color: "var(--color-text-primary)" }}>{title}</h3>{children}</div>; }
function Th({ children }: { children: React.ReactNode }) { return <th className="px-4 py-3 text-left text-[10px] uppercase tracking-wide font-bold">{children}</th>; }
